# configuration affecting the single LIRs
lirs:
  # suffix of the file name(s) containing the phosphorylation sites in the LIR
  outpsitessuffix: -phosphosites
  # number of flanking residues to be considered on the left of the LIR
  lcontext: 8
  # number of flanking residues to be considered on the right of the LIR
  rcontext: 8

  # configuration affecting the LIR variants
  variants:
    # suffix of the file names(s) containing all variants
    outsuffix: -variants
    # residues used to replace those in phosphoryation sites
    substitutions:
      "S": E
      # better replacements than glutamate should be used 
      # for threonines and tyrosines
      "T": E
      "Y": E

# iLIR configuration
ilir:
  # path to the iLIR wrapper
  executable: /data/tools_scripts_repository/CBL-scripts/CBL-SB/ilir/ilir
  # name of the directory that will contain all iLIR results 
  # (the same directory name will be used both for the results
  # of the wild-type and for those of the variants)
  dirname: ilir
  # suffix to be used for iLIR output files
  outsuffix: -ilir

# NetPhos configuration
netphos:
  # path to the NetPhos executable
  executable: netphos
  # name of the directory that will contain the NetPhos results
  dirname: netphos
  # suffix to be used for raw output files
  rawoutsuffix: -netphos
  # suffix to be used for processed output files
  procoutsuffix: -netphos_processed

# Spider3 configuration
spider3:
  # whehter to run Spider3 for the wild-type protein and all variants
  run: True
  # path to the Spider3 executable
  executable: spider3
  # name of the directory that will contain all Spider3 results 
  # (the same directory name will be used both for the results 
  # of the wild-type and for those of the variants)
  dirname: spider3
  # data aggregation configuration
  aggregation:
    # suffix for the aggregated output files
    outsuffix: -spider3

# PSIPRED configuration
psipred:
  # whether to run PSIPRED for the wild-type protein and all variants
  run: True
  # path to the PSIPRED executable
  executable: /usr/local/psipred/runpsipred
  # name of the directory that will contain all PSIPRED results 
  # (the same directory name will be used both for the results 
  # of the wild-type and for those of the variants)
  dirname: psipred
  # data aggregation configuration
  aggregation:
    # suffix for the aggregated output files
    outsuffix: -psipred
    # color maps to be used to show the propensities for the
    # different secondary structures in the HTML aggregation file 
    # (Coil, Helix, Strand)
    cmaps: Blues, Greens, Oranges
    # length of each chunk of residues to be shown on each line
    # in the HTML aggregation file (especially useful for really
    # long protein sequences)
    chunksize: 20
